services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - DEBUG=1
    command: uvicorn halum_hut.asgi:application --host 0.0.0.0 --port 8000 --reload

  celery:
    build: .
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - DEBUG=1
    command: celery -A halum_hut worker --loglevel=info
